package dev

import (
	core "dappco.re/go"
	"slices"
	"testing"

	"dappco.re/go/io"
)

func TestRunTestGen_Good(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv("CORE_WORKING_DIRECTORY", tmpDir)

	serviceDir := core.PathJoin(tmpDir, "pkg", "demo")
	if err := io.Local.EnsureDir(serviceDir); err != nil {
		t.Fatalf("create service dir: %v", err)
	}
	if err := io.Local.Write(core.PathJoin(serviceDir, "demo.go"), `package demo

type Example struct{}

const Answer = 42

var Value = Example{}

func Run() {}
`); err != nil {
		t.Fatalf("write demo.go: %v", err)
	}
	if err := io.Local.Write(core.PathJoin(serviceDir, "extra.go"), `package demo

type Another struct{}

func Extra() {}
`); err != nil {
		t.Fatalf("write extra.go: %v", err)
	}
	if err := io.Local.Write(core.PathJoin(serviceDir, "demo_test.go"), `package demo

func Ignored() {}
`); err != nil {
		t.Fatalf("write demo_test.go: %v", err)
	}

	if r := runTestGen(); !r.OK {
		t.Fatalf("run test generator: %v", r.Value)
	}

	generatedPath := core.PathJoin(tmpDir, "demo", "demo_test.go")
	content, err := io.Local.Read(generatedPath)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}

	for _, want := range []string{
		`// Code generated by "core dev api test-gen"; DO NOT EDIT.`,
		`package demo`,
		`impl "dappco.re/go/cli/demo"`,
		`type _ = impl.Example`,
		`type _ = impl.Another`,
		`const _ = impl.Answer`,
		`var _ = impl.Value`,
		`var _ = impl.Run`,
		`var _ = impl.Extra`,
	} {
		if !core.Contains(content, want) {
			t.Fatalf("generated content missing %q", want)
		}
	}
	if core.Contains(content, `Ignored`) {
		t.Fatal("generated content includes ignored symbol")
	}
}

func TestGeneratePublicAPITestFile_Good(t *testing.T) {
	tmpDir := t.TempDir()

	if r := generatePublicAPITestFile(
		core.PathJoin(tmpDir, "demo"),
		core.PathJoin(tmpDir, "demo", "demo_test.go"),
		"demo",
		[]symbolInfo{
			{Name: "Example", Kind: "type"},
			{Name: "Answer", Kind: "const"},
		},
	); !r.OK {
		t.Fatalf("generate public API test file: %v", r.Value)
	}

	content, err := io.Local.Read(core.PathJoin(tmpDir, "demo", "demo_test.go"))
	if err != nil {
		t.Fatalf("read generated public API test file: %v", err)
	}

	for _, want := range []string{`type _ = impl.Example`, `const _ = impl.Answer`} {
		if !core.Contains(content, want) {
			t.Fatalf("generated content missing %q", want)
		}
	}
}

func TestGetExportedSymbolsMultiFile(t *testing.T) {
	tmpDir := t.TempDir()

	serviceDir := core.PathJoin(tmpDir, "demo")
	if err := io.Local.EnsureDir(serviceDir); err != nil {
		t.Fatalf("create service dir: %v", err)
	}
	if err := io.Local.Write(core.PathJoin(serviceDir, "demo.go"), `package demo

type Example struct{}

const Answer = 42
`); err != nil {
		t.Fatalf("write demo.go: %v", err)
	}
	if err := io.Local.Write(core.PathJoin(serviceDir, "extra.go"), `package demo

var Value = Example{}

func Run() {}
`); err != nil {
		t.Fatalf("write extra.go: %v", err)
	}
	if err := io.Local.Write(core.PathJoin(serviceDir, "demo_test.go"), `package demo

type Ignored struct{}
`); err != nil {
		t.Fatalf("write demo_test.go: %v", err)
	}

	symbols, r := getExportedSymbols(serviceDir)
	if !r.OK {
		t.Fatalf("get exported symbols: %v", r.Value)
	}
	want := []symbolInfo{
		{Name: "Answer", Kind: "const"},
		{Name: "Example", Kind: "type"},
		{Name: "Run", Kind: "func"},
		{Name: "Value", Kind: "var"},
	}
	if !slices.Equal(symbols, want) {
		t.Fatalf("symbols = %v, want %v", symbols, want)
	}
}
