package dev

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"dappco.re/go/core/io"
)

func TestRunTestGen_Good(t *testing.T) {
	tmpDir := t.TempDir()

	originalWD, err := os.Getwd()
	require.NoError(t, err)
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})
	require.NoError(t, os.Chdir(tmpDir))

	serviceDir := filepath.Join(tmpDir, "pkg", "demo")
	require.NoError(t, io.Local.EnsureDir(serviceDir))
	require.NoError(t, io.Local.Write(filepath.Join(serviceDir, "demo.go"), `package demo

type Example struct{}

const Answer = 42

var Value = Example{}

func Run() {}
`))
	require.NoError(t, io.Local.Write(filepath.Join(serviceDir, "extra.go"), `package demo

type Another struct{}

func Extra() {}
`))
	require.NoError(t, io.Local.Write(filepath.Join(serviceDir, "demo_test.go"), `package demo

func Ignored() {}
`))

	require.NoError(t, runTestGen())

	generatedPath := filepath.Join(tmpDir, "demo", "demo_test.go")
	content, err := io.Local.Read(generatedPath)
	require.NoError(t, err)

	require.Contains(t, content, `// Code generated by "core dev api test-gen"; DO NOT EDIT.`)
	require.Contains(t, content, `package demo`)
	require.Contains(t, content, `impl "dappco.re/go/core/cli/demo"`)
	require.Contains(t, content, `type _ = impl.Example`)
	require.Contains(t, content, `type _ = impl.Another`)
	require.Contains(t, content, `const _ = impl.Answer`)
	require.Contains(t, content, `var _ = impl.Value`)
	require.Contains(t, content, `var _ = impl.Run`)
	require.Contains(t, content, `var _ = impl.Extra`)
	require.NotContains(t, content, `Ignored`)
}

func TestGeneratePublicAPITestFile_Good(t *testing.T) {
	tmpDir := t.TempDir()

	require.NoError(t, generatePublicAPITestFile(
		filepath.Join(tmpDir, "demo"),
		filepath.Join(tmpDir, "demo", "demo_test.go"),
		"demo",
		[]symbolInfo{
			{Name: "Example", Kind: "type"},
			{Name: "Answer", Kind: "const"},
		},
	))

	content, err := io.Local.Read(filepath.Join(tmpDir, "demo", "demo_test.go"))
	require.NoError(t, err)

	require.True(t, strings.Contains(content, `type _ = impl.Example`))
	require.True(t, strings.Contains(content, `const _ = impl.Answer`))
}

func TestGetExportedSymbols_Good_MultiFile(t *testing.T) {
	tmpDir := t.TempDir()

	serviceDir := filepath.Join(tmpDir, "demo")
	require.NoError(t, io.Local.EnsureDir(serviceDir))
	require.NoError(t, io.Local.Write(filepath.Join(serviceDir, "demo.go"), `package demo

type Example struct{}

const Answer = 42
`))
	require.NoError(t, io.Local.Write(filepath.Join(serviceDir, "extra.go"), `package demo

var Value = Example{}

func Run() {}
`))
	require.NoError(t, io.Local.Write(filepath.Join(serviceDir, "demo_test.go"), `package demo

type Ignored struct{}
`))

	symbols, err := getExportedSymbols(serviceDir)
	require.NoError(t, err)
	require.Equal(t, []symbolInfo{
		{Name: "Answer", Kind: "const"},
		{Name: "Example", Kind: "type"},
		{Name: "Run", Kind: "func"},
		{Name: "Value", Kind: "var"},
	}, symbols)
}
